### ISSUE TITLE
User timezone appearing after name (not consistent individual vs Team invite)

### ISSUE THREAD

**Issue by b4ps** [Mobility4PS/Rocket.Chat#28]
Chris is the only member invited who is not part of the team and the only one with timezone showing behind his name.

![image](https://user-images.githubusercontent.com/57500558/93251873-657c8c80-f75a-11ea-897f-cc4af6363b0f.png)

**Comment by cprice-kgi** [comment]
we discovered the timezone is only shown for users who are not in your (current user's) time zone. this is intended behavior.
