### ISSUE TITLE
BUILD 3.6.0 - can't view the Directory. Just shows a blank screen

### ISSUE THREAD

**Issue by b4ps** [Mobility4PS/Rocket.Chat#5]
![image](https://user-images.githubusercontent.com/57500558/92272593-7225f880-eeaf-11ea-8d52-8aae3a1eeb83.png)

**Comment by b4ps** [comment]
@cprice-kgi we can't continue to test teams since the Directory is not viewable. All we can do is create one and add it to a channel. Can you look into this issue so we can continue testing Teams?

**Comment by cprice-kgi** [comment]
this should be resolved now on the build server. some of the teams code integration needed to be modified to work with the new 3.6.0 structure.
